services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
  api:
    build: ./api
    environment:
      NODE_ENV: development
      PORT: 8080
      MONGO_URI: mongodb://mongo:27017/helpdesk
      JWT_SECRET: change-me
      AUTO_CLOSE_ENABLED: 'true'
      CONFIDENCE_THRESHOLD: '0.78'
      STUB_MODE: 'true'
    ports:
      - '8080:8080'
    depends_on:
      - mongo
    restart: unless-stopped
  client:
    build: ./client
    environment:
      VITE_API_URL: http://localhost:8080
    ports:
      - '5173:5173'
    depends_on:
      - api
    restart: unless-stopped
volumes:
  mongo-data:

